FROM debian

RUN apt-get update
RUN apt-get full-upgrade -y
RUN apt-get install -y as31
RUN apt-get install -y gcc-6
RUN apt-get install -y gfortran-6
RUN apt-get install -y open-cobol
RUN apt-get install -y golang-1.8
RUN apt-get install -y fp-compiler-3.0.0
RUN apt-get install -y scala
RUN apt-get install -y haskell-platform
RUN apt-get install -y python3
RUN apt-get install -y ruby2.3
RUN apt-get install -y gcl
RUN apt-get install -y tinyscheme

RUN mkdir /study
